import { useMemo, useState, type ComponentType } from "react";
import {
  Atom, BookMarked, BookOpen, BookOpenCheck, BookOpenText, BrainCircuit, ChevronDown, ChevronLeft,
  Compass, Dna, ExternalLink, Facebook, FileQuestion, FileText, FlaskConical, Github, Globe2,
  GraduationCap, HeartHandshake, Home, Languages, Library, Linkedin, Mail, PlayCircle, Quote, Scale,
  ScrollText, Send, Sigma, Sparkles, Target, Type,
} from "lucide-react";
import PromptLibrary from "@/components/PromptLibrary";
import { examChannels, materials, resourceCategories, type MaterialCatalog, type ResourceCard } from "@/data/richCatalog";
import { unitExpansions, type UnitLink } from "@/data/unitExpansions";

type IconType = ComponentType<{ className?: string; strokeWidth?: number }>;
type View = "home" | "subjects" | "prompts" | "resources" | "exams";
type ResourceMode = "sources" | "units";
const PROFILE_IMAGE_URL = "https://alharethprofilo.netlify.app/assets/alhareth-profile.webp";
const subjectIcons: Record<string, IconType> = { "رياضيات": Sigma, "فيزياء": Atom, "كيمياء": FlaskConical, "أحياء": Dna, "لغة إنجليزية": Languages, "نحو وصرف": Type, "أدب ونصوص وبلاغة": BookOpenText, "قراءة": BookMarked, "قرآن كريم": ScrollText, "حديث وتهذيب": Quote, "إيمان": HeartHandshake, "فقه": Scale, "سيرة نبوية": Compass };
const subjectTone: Record<string, string> = { "رياضيات": "bg-violet-50 text-violet-700", "فيزياء": "bg-blue-50 text-blue-700", "كيمياء": "bg-emerald-50 text-emerald-700", "أحياء": "bg-teal-50 text-teal-700", "لغة إنجليزية": "bg-amber-50 text-amber-700", "نحو وصرف": "bg-rose-50 text-rose-700", "أدب ونصوص وبلاغة": "bg-fuchsia-50 text-fuchsia-700", "قراءة": "bg-orange-50 text-orange-700" };
const categoryIcons: Record<string, IconType> = { books: BookOpenCheck, youtube: PlayCircle, telegram: Send, tests: FileQuestion, reviews: FileText };
const viewTitles: Record<View, string> = { home: "الرئيسية", subjects: "المواد", prompts: "البرومبتات", resources: "المصادر", exams: "المحاكاة" };
const socialLinks = [
  { label: "الموقع الشخصي", href: "https://alharethprofilo.netlify.app/", icon: Globe2 }, { label: "GitHub", href: "https://github.com/Alhareith", icon: Github },
  { label: "LinkedIn", href: "https://www.linkedin.com/in/%D8%A7%D9%84%D8%AD%D8%A7%D8%B1%D8%AB-%D8%A7%D9%84%D8%AF%D8%A7%D9%87%D9%8A%D8%A9-95b4a831a", icon: Linkedin },
  { label: "Hugging Face", href: "https://huggingface.co/Alhareth7790", icon: Sparkles }, { label: "Telegram", href: "https://t.me/devhareth", icon: Send },
  { label: "Facebook", href: "https://www.facebook.com/alharth.aldahyt/", icon: Facebook }, { label: "البريد", href: "mailto:alhareithaldahia@gmail.com", icon: Mail },
];

export default function HomeV3() {
  const [view, setView] = useState<View>("home"); const [selectedId, setSelectedId] = useState("رياضيات"); const [filter, setFilter] = useState("all"); const [resourceMode, setResourceMode] = useState<ResourceMode>("sources");
  const selected = materials.find((material) => material.id === selectedId) ?? materials[0];
  const selectedUnits = useMemo(() => unitExpansions.filter((unit) => unit.subjectId === selected.id), [selected.id]);
  const selectedUnitTitles = useMemo(() => selectedUnits.map((unit) => unit.title), [selectedUnits]);
  const visibleSources = useMemo(() => filter === "all" ? selected.sources : selected.sources.filter((source) => source.category === filter), [filter, selected]);
  const go = (next: View) => { setView(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const chooseSubject = (material: MaterialCatalog) => { setSelectedId(material.id); setFilter("all"); setResourceMode("sources"); go("home"); };
  return <div dir="rtl" className="min-h-screen bg-[#f5f6fa] pb-24 font-sans text-slate-950 md:pb-0">
    <AppHeader view={view} onNavigate={go} /><main className="min-h-[70vh]">
      {view === "home" && <HomeView selected={selected} onNavigate={go} />}
      {view === "subjects" && <SubjectsView selectedId={selected.id} onSelect={chooseSubject} />}
      {view === "prompts" && <PromptLibrary subject={selected.title} units={selectedUnitTitles} />}
      {view === "resources" && <ResourcesView selected={selected} selectedUnits={selectedUnits} visibleSources={visibleSources} filter={filter} onFilter={setFilter} mode={resourceMode} onMode={setResourceMode} onChangeSubject={() => go("subjects")} />}
      {view === "exams" && <ExamsView />}
    </main>{view !== "prompts" && <DeveloperFooter />}<MobileTabs view={view} onNavigate={go} />
  </div>;
}

function AppHeader({ view, onNavigate }: { view: View; onNavigate: (view: View) => void }) {
  return <header className="sticky top-0 z-50 border-b border-slate-200 bg-white/95 backdrop-blur-xl"><div className="mx-auto flex h-[64px] max-w-6xl items-center justify-between px-4 sm:px-6">
    <button type="button" onClick={() => onNavigate("home")} className="flex items-center gap-2.5 text-right"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-950 text-white"><BookOpen className="h-4.5 w-4.5" /></span><span><strong className="block text-sm font-black text-slate-950">دليل الثالث</strong><small className="block text-[10px] font-bold text-slate-400">{viewTitles[view]}</small></span></button>
    <nav className="hidden items-center gap-1 rounded-2xl bg-slate-100 p-1 md:flex" aria-label="أقسام الموقع"><DesktopTab active={view === "home"} onClick={() => onNavigate("home")} label="الرئيسية" /><DesktopTab active={view === "prompts"} onClick={() => onNavigate("prompts")} label="البرومبتات" /><DesktopTab active={view === "exams"} onClick={() => onNavigate("exams")} label="المحاكاة" /><DesktopTab active={view === "subjects"} onClick={() => onNavigate("subjects")} label="المواد" /><DesktopTab active={view === "resources"} onClick={() => onNavigate("resources")} label="المصادر" /></nav>
    <div className="flex min-h-10 items-center gap-2 rounded-full border border-emerald-100 bg-emerald-50 px-3 text-[10px] font-extrabold text-emerald-800"><span className="h-2 w-2 rounded-full bg-emerald-500" />خذها بهدوء · خطوة واحدة الآن</div>
  </div></header>;
}
function DesktopTab({ active, onClick, label }: { active: boolean; onClick: () => void; label: string }) { return <button type="button" onClick={onClick} className={`rounded-xl px-3 py-2 text-xs font-extrabold ${active ? "bg-white text-slate-950 shadow-sm" : "text-slate-500 hover:text-slate-900"}`}>{label}</button>; }

function HomeView({ selected, onNavigate }: { selected: MaterialCatalog; onNavigate: (view: View) => void }) {
  const Icon = subjectIcons[selected.id] ?? BookOpenText; const tone = subjectTone[selected.id] ?? "bg-slate-100 text-slate-700";
  return <div className="mx-auto max-w-5xl px-4 py-5 sm:px-6 sm:py-8">
    <section className="rounded-[28px] bg-slate-950 p-5 text-white sm:p-8"><span className="inline-flex items-center gap-2 text-[11px] font-extrabold text-violet-300"><GraduationCap className="h-4 w-4" /> الثالث الثانوي · اليمن</span><h1 className="mt-3 text-2xl font-black leading-10 sm:text-3xl">افهم، ثم اختبر نفسك.</h1><p className="mt-2 max-w-xl text-sm font-medium leading-7 text-slate-300">لا تحتاج أن تعرف كيف تستخدم الموقع. ابدأ من إحدى الخطوتين أدناه: اطلب شرحًا جاهزًا، أو ادخل محاكاة تقيس مستواك وتخبرك ماذا تراجع.</p></section>
    <button type="button" onClick={() => onNavigate("subjects")} className="mt-4 flex w-full items-center gap-3 rounded-2xl border border-slate-200 bg-white p-3.5 text-right"><span className={`flex h-10 w-10 items-center justify-center rounded-2xl ${tone}`}><Icon className="h-5 w-5" /></span><span className="flex-1"><small className="block text-[9px] font-extrabold text-slate-400">المادة الحالية</small><strong className="text-sm font-black">{selected.title}</strong></span><span className="text-[10px] font-extrabold text-violet-700">تغيير</span></button>
    <section className="mt-4 grid gap-3 sm:grid-cols-2">
      <button type="button" onClick={() => onNavigate("prompts")} className="group rounded-[26px] border border-violet-200 bg-white p-5 text-right shadow-[0_12px_35px_rgba(15,23,42,.05)] transition hover:-translate-y-0.5"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-100 text-violet-700"><BrainCircuit className="h-6 w-6" /></span><small className="mt-5 block text-[10px] font-extrabold text-violet-700">إذا لم تفهم أو توقفت في سؤال</small><strong className="mt-1 block text-xl font-black">استخدم برومبت جاهز</strong><p className="mt-2 text-xs font-medium leading-6 text-slate-500">اختر حالتك، الصق سؤالك، وانسخ تعليمات جاهزة تطلب شرحًا عربيًا مناسبًا للمنهج.</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-extrabold text-violet-700">ابدأ الشرح <ChevronLeft className="h-4 w-4" /></span></button>
      <a href="#exam-pilot" className="group rounded-[26px] bg-slate-950 p-5 text-right text-white shadow-[0_12px_35px_rgba(15,23,42,.1)] transition hover:-translate-y-0.5"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10 text-violet-200"><Target className="h-6 w-6" /></span><small className="mt-5 block text-[10px] font-extrabold text-violet-300">إذا تريد تعرف مستواك الآن</small><strong className="mt-1 block text-xl font-black">ابدأ المحاكاة</strong><p className="mt-2 text-xs font-medium leading-6 text-slate-300">٥٠ سؤالًا · ساعة واحدة عند اختيار المؤقت · حفظ واستكمال · تحليل يوجهك بعد التسليم.</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-extrabold text-violet-200">اختبر نفسك <ChevronLeft className="h-4 w-4" /></span></a>
    </section>
    <section className="mt-6"><div className="mb-2 flex items-center justify-between"><span className="text-[10px] font-extrabold text-slate-400">بعد الفهم والاختبار</span><span className="text-[10px] font-bold text-slate-400">أدوات مساندة</span></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><ActionRow icon={Library} title="المصادر والشروحات" description="كتب وفيديوهات وقنوات مرتبة حسب المادة." onClick={() => onNavigate("resources")} /><ActionRow icon={BookOpenCheck} title="المواد والوحدات" description="غيّر المادة أو انتقل إلى وحداتها ومراجعها." onClick={() => onNavigate("subjects")} /></div></section>
  </div>;
}
function ActionRow({ icon: Icon, title, description, onClick }: { icon: IconType; title: string; description: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="flex w-full items-center gap-3 border-b border-slate-100 p-4 text-right last:border-0 hover:bg-slate-50"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-100 text-slate-600"><Icon className="h-4.5 w-4.5" /></span><span className="flex-1"><strong className="block text-sm font-black">{title}</strong><span className="mt-1 block text-xs font-medium text-slate-500">{description}</span></span><ChevronLeft className="h-5 w-5 text-slate-300" /></button>; }

function SubjectsView({ selectedId, onSelect }: { selectedId: string; onSelect: (material: MaterialCatalog) => void }) { return <div className="mx-auto max-w-4xl px-4 py-5 sm:px-6 sm:py-8"><PageHeading title="اختر المادة" description="اختيارك يحدد سياق البرومبتات والمصادر." /><div className="mt-5 overflow-hidden rounded-3xl border border-slate-200 bg-white">{materials.map((material) => { const Icon = subjectIcons[material.id] ?? BookOpenText; const tone = subjectTone[material.id] ?? "bg-slate-100 text-slate-700"; const active = selectedId === material.id; return <button key={material.id} type="button" onClick={() => onSelect(material)} className={`flex w-full items-center gap-3 border-b border-slate-100 p-4 text-right last:border-0 sm:p-5 ${active ? "bg-violet-50/50" : "hover:bg-slate-50"}`}><span className={`flex h-11 w-11 items-center justify-center rounded-2xl ${tone}`}><Icon className="h-5 w-5" /></span><span className="flex-1"><strong className="block text-sm font-black">{material.title}</strong><span className="text-xs text-slate-500">{material.sources.length} مصادر</span></span>{active && <span className="rounded-full bg-violet-100 px-2 py-1 text-[9px] font-extrabold text-violet-700">الحالية</span>}<ChevronLeft className="h-5 w-5 text-slate-300" /></button>; })}</div></div>; }

function ResourcesView({ selected, selectedUnits, visibleSources, filter, onFilter, mode, onMode, onChangeSubject }: { selected: MaterialCatalog; selectedUnits: ReturnType<typeof unitExpansions.filter>; visibleSources: ResourceCard[]; filter: string; onFilter: (value: string) => void; mode: ResourceMode; onMode: (mode: ResourceMode) => void; onChangeSubject: () => void }) {
  return <div className="mx-auto max-w-5xl px-4 py-5 sm:px-6 sm:py-8"><div className="flex items-end justify-between gap-3"><PageHeading title={`مصادر ${selected.title}`} description="المصادر تأتي بعد البرومبت والمحاكاة: افتحها عندما تعرف ما الذي تحتاج مراجعته." /><button type="button" onClick={onChangeSubject} className="mb-1 rounded-xl bg-white px-3 py-2 text-[10px] font-extrabold text-violet-700 ring-1 ring-slate-200">تغيير المادة</button></div><div className="mt-5 grid grid-cols-2 rounded-2xl bg-slate-200/70 p-1"><button type="button" onClick={() => onMode("sources")} className={`min-h-10 rounded-xl text-xs font-extrabold ${mode === "sources" ? "bg-white shadow-sm" : "text-slate-500"}`}>المصادر</button><button type="button" onClick={() => onMode("units")} className={`min-h-10 rounded-xl text-xs font-extrabold ${mode === "units" ? "bg-white shadow-sm" : "text-slate-500"}`}>حسب الوحدة</button></div>
    {mode === "sources" ? <><div className="-mx-4 mt-4 flex gap-2 overflow-x-auto px-4 pb-2 sm:mx-0 sm:px-0">{resourceCategories.map((category) => { const count = category.id === "all" ? selected.sources.length : selected.sources.filter((source) => source.category === category.id).length; if (category.id !== "all" && count === 0) return null; return <button key={category.id} type="button" onClick={() => onFilter(category.id)} className={`shrink-0 rounded-full border px-3.5 py-2 text-[11px] font-extrabold ${filter === category.id ? "border-slate-950 bg-slate-950 text-white" : "border-slate-200 bg-white text-slate-600"}`}>{category.label} · {count}</button>; })}</div><div className="mt-3 overflow-hidden rounded-3xl border border-slate-200 bg-white">{visibleSources.map((source) => <ResourceRow key={source.id} source={source} />)}</div></> : <div className="mt-4 space-y-3">{selectedUnits.length ? selectedUnits.map((unit, index) => <details key={unit.title} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white" open={index === 0}><summary className="flex cursor-pointer list-none items-start gap-3 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-950 text-xs font-black text-white">{index + 1}</span><span className="flex-1"><small className="text-[9px] font-extrabold text-violet-700">{unit.label}</small><strong className="block text-sm font-black">{unit.title}</strong><span className="text-xs text-slate-500">{unit.note}</span></span><ChevronDown className="h-4 w-4 text-slate-400" /></summary><div className="divide-y border-t border-slate-100">{unit.links.map((link) => <UnitRow key={`${unit.title}-${link.title}`} link={link} />)}</div></details>) : <div className="rounded-3xl border bg-white p-6 text-center text-xs text-slate-500">لا توجد وحدات مفهرسة بعد.</div>}</div>}
  </div>;
}
function ResourceRow({ source }: { source: ResourceCard }) { const Icon = categoryIcons[source.category] ?? FileText; return <a href={source.url} target="_blank" rel="noreferrer" className="flex items-center gap-3 border-b border-slate-100 p-4 text-right last:border-0 hover:bg-slate-50"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-100"><Icon className="h-4.5 w-4.5" /></span><span className="flex-1"><small className="text-[9px] font-extrabold text-violet-700">{source.badge}</small><strong className="block text-xs font-black">{source.title}</strong><span className="text-[11px] text-slate-500">{source.detail || source.platform}</span></span><ExternalLink className="h-4 w-4 text-slate-300" /></a>; }
function UnitRow({ link }: { link: UnitLink }) { return <a href={link.url} target="_blank" rel="noreferrer" className="flex items-center gap-3 p-4"><span className="flex-1"><small className="text-[9px] font-extrabold text-violet-700">{link.kind}</small><strong className="block text-xs font-black">{link.title}</strong></span><ExternalLink className="h-4 w-4 text-slate-300" /></a>; }

function ExamsView() { return <div className="mx-auto max-w-4xl px-4 py-5 sm:px-6 sm:py-8"><PageHeading title="المحاكاة" description="اختبر نفسك أولًا، ثم استخدم التحليل لمعرفة ما الذي تراجعه." /><a href="#exam-pilot" className="mt-5 block rounded-3xl bg-slate-950 p-5 text-white"><small className="text-[10px] font-extrabold text-violet-300">متاحة الآن</small><strong className="mt-1 block text-lg font-black">محاكاة التفاضل والتكامل</strong><span className="mt-1 block text-xs text-slate-300">٥٠ سؤالًا · ٨٠ درجة · ساعة واحدة عند اختيار المؤقت · تحليل ومراجعة موجهة.</span></a><div className="mt-6"><span className="text-[10px] font-extrabold text-slate-400">مصادر اختبارات إضافية</span><div className="mt-2 overflow-hidden rounded-3xl border bg-white">{examChannels.map((channel) => <a key={channel.url} href={channel.url} target="_blank" rel="noreferrer" className="flex items-center gap-3 border-b p-4 last:border-0"><span className="flex-1"><small className="text-[9px] font-extrabold text-amber-700">{channel.badge}</small><strong className="block text-sm font-black">{channel.title}</strong></span><ExternalLink className="h-4 w-4 text-slate-300" /></a>)}</div></div></div>; }
function PageHeading({ title, description }: { title: string; description: string }) { return <div><h1 className="text-2xl font-black">{title}</h1><p className="mt-1 text-sm leading-7 text-slate-500">{description}</p></div>; }
function DeveloperFooter() { return <footer className="mt-8 border-t border-slate-200 bg-white px-4 py-8"><div className="mx-auto max-w-5xl"><a href="https://alharethprofilo.netlify.app/" target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3 ring-1 ring-slate-100"><img src={PROFILE_IMAGE_URL} alt="الحارث الداهية" className="h-12 w-12 rounded-2xl object-cover" /><span className="flex-1"><small className="text-[9px] font-extrabold text-violet-700">تصميم وتطوير</small><strong className="block text-sm font-black">الحارث الداهية</strong></span><ExternalLink className="h-4 w-4" /></a><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{socialLinks.map((social) => { const Icon = social.icon; return <a key={social.label} href={social.href} target={social.href.startsWith("mailto:") ? undefined : "_blank"} rel="noreferrer" className="flex min-h-10 items-center justify-center gap-2 rounded-xl border px-2 text-[10px] font-extrabold text-slate-600"><Icon className="h-3.5 w-3.5" />{social.label}</a>; })}</div></div></footer>; }
function MobileTabs({ view, onNavigate }: { view: View; onNavigate: (view: View) => void }) { return <nav className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-5 border-t border-slate-200 bg-white/98 px-1 pb-[max(6px,env(safe-area-inset-bottom))] pt-1.5 md:hidden"><MobileTab icon={Home} label="الرئيسية" active={view === "home"} onClick={() => onNavigate("home")} /><MobileTab icon={Sparkles} label="البرومبتات" active={view === "prompts"} onClick={() => onNavigate("prompts")} /><MobileTab icon={Target} label="المحاكاة" active={view === "exams"} onClick={() => onNavigate("exams")} /><MobileTab icon={Library} label="المواد" active={view === "subjects"} onClick={() => onNavigate("subjects")} /><MobileTab icon={BookOpenCheck} label="المصادر" active={view === "resources"} onClick={() => onNavigate("resources")} /></nav>; }
function MobileTab({ icon: Icon, label, active, onClick }: { icon: IconType; label: string; active: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={`flex min-h-[54px] flex-col items-center justify-center gap-1 rounded-xl text-[9px] font-extrabold ${active ? "text-violet-700" : "text-slate-400"}`}><Icon className="h-[18px] w-[18px]" />{label}</button>; }
